print('Welcome to the tip calculator.')
totalBill = float(input('What was the total bill? $'))
billSplit = int(input('How many people to split the bill? '))
tipPercentage = int(input('What percentage tip would you like to give? 10, 12, or 15? '))
newAmount = totalBill + ((tipPercentage/100) * totalBill)
print('Each person should pay: $',round(newAmount/billSplit,1))